[package]
authors = ["Evan La Fontaine <navelafontaine@gmail.com>", "Jonah Hopkin <turtle@turtle.business>"]
edition = "2024"
readme = "README.md"
name = "embedded-common"
version = "0.1.0"

[dependencies]
embedded-io = "0.6.1"
fugit = "0.3.9"
# stm32g4 = { version = "0.16.0", features = ["rt", "stm32g474"] }
# stm32g4xx-hal patched in below; original is https://github.com/stm32-rs/stm32g4xx-hal
stm32g4xx-hal = {
    version = "0.0.3",
    git = "https://github.com/bluesatunsw/stm32g4xx-hal",
    # additional features enabled by this crate's features
    features = ["rt"]
}
nb = "1.1.0"
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
bitfield-struct = { version = "0.12.1", optional = true }
canadensis_core = { version = "0.5.0" }
# CAN-FD
canadensis = { version = "0.5.0", optional = true }
canadensis_can = {
    version = "0.5.1",
    features = ["can-fd"],
    optional = true
}
fdcan = {
    # This is, again, a Bluesat special. We need delay compensation and Evan's fixes
    version = "0.4.0",
    git = "https://github.com/bluesatunsw/fdcan",
    optional = true
}

[features]
can-fd = ["dep:canadensis_can", "dep:fdcan", "stm32g4xx-hal/can", "dep:canadensis"]
stm32g431 = ["stm32g4xx-hal/stm32g431"]
stm32g474 = ["stm32g4xx-hal/stm32g474"]
dprintln-enabled = []
stepper-board = ["bitfield-struct"]
